version: '2'
services:
    user-service:
        build: ./user-service
        ports:
            - "8123:8123"
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
    db:
        build: ./test-database
